### PR TITLE
Cleanup simulation

### PR DESCRIPTION
**Pull request by simone-silvestri**
remove excess flexibility and add it where needed

### CODE REVIEW

**Comment by glwagner** [comment]
There's also a neverworld implementation in ClimaOcean

**Comment by simone-silvestri** [comment]
We decided on Friday to go ahead with this setup since the people using it are already familiar, and we have results we deem plausible.

I guess in the meantime we can make sure that the same results are obtained in ClimaOcean

**Comment by sandreza** [comment]
I accept

**Review by sandreza — APPROVED** [review]
looks good

**Pull request merged**
